### ISSUE TITLE
MD5 Digest

### ISSUE THREAD

**Issue by jbcrosby** [Nuix/Regex-Scanner#5]
Not an issue but a question:  Is there a method/function that will pull the MD5 value for the doc?  getMD5 didn't work, I didn't try others.  Thanks!

**Comment by nuix-mrk** [comment]
You'd need to edit the code to call Item.getDigests().getMd5().
see: https://download.nuix.com/releases/desktop/stable/docs/en/scripting/api/nuix/Item.html#getDigests()
https://download.nuix.com/releases/desktop/stable/docs/en/scripting/api/nuix/DigestCollection.html
